[[headers]]
    for  ="/*"
    [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/; frame-src https://www.google.com/recaptcha/; style-src 'self' *.cloudfront.net; media-src 'self' *.cloudfront.net; img-src 'self' *.cloudfront.net"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-Xss-Protection = "1; mode=block;"